name: CI-android

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - windows-2022
          - macos-12
        qt:
          - version: "5.15.2"
            modules:
            example-archives: qtbase qtsensors
            example-modules:
          - version: "6.3.2"
            modules: qtsensors
            example-archives: qtbase
            example-modules:  qtsensors

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: action/

      - run: |
          cd action
          npm ci || npm install
        shell: bash

      - run: |
          cd action
          npm run build

      - name: Install Qt
        uses: ./
        with:
          target: android
          modules: ${{ matrix.qt.modules }}
          version: ${{ matrix.qt.version }}
          examples: true
          example-archives: ${{ matrix.qt.example-archives }}
          example-modules:  ${{ matrix.qt.example-modules }}

      - name: Configure test project on windows
        if: ${{ startsWith(matrix.os, 'windows') }}
        env:
          QT_VERSION: ${{ matrix.qt.version }}
        run: |
          cd ..\Qt\Examples\Qt-%QT_VERSION%\sensors\accelbubble
          for /f "delims=" %%d in ( 'vswhere.exe -latest -property installationPath' ) do @( call "%%d\VC\Auxiliary\Build\vcvars64.bat" )
          if "%QT_VERSION:~0,1%"=="6" (
            cmake -S . -B .\build
          ) else (
            qmake
          )
        shell: cmd

      - name: Configure test project on unix
        if: ${{ !startsWith(matrix.os, 'windows') }}
        env:
          QT_VERSION: ${{ matrix.qt.version }}
        run: |
          cd ../Qt/Examples/Qt-${{ matrix.qt.version }}/sensors/accelbubble
          if [[ $QT_VERSION == 6* ]]; then
            cmake -S . -B ./build
          else
            qmake
          fi
        shell: bash
